### ISSUE TITLE
N900: screen rotation segfaults in sgx_exa_update_pixmap

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#578]
Rotating the screen, e.g. with 

`xrandr -o right`

Crashes the X in `sgx_exa_update_pixmap` in https://github.com/maemo-leste/xf86-video-pvrsgx/

```
(gdb) bt
#0  0xb6716e96 in sgx_exa_update_pixmap () from /usr/lib/xorg/modules/drivers/pvrsgx_drv.so
#1  0xb67187b8 in update_flip_pixmaps () from /usr/lib/xorg/modules/drivers/pvrsgx_drv.so
#2  0xb6718814 in PVR2D_PostFBReset () from /usr/lib/xorg/modules/drivers/pvrsgx_drv.so
#3  0xb670981a in post_fb_reset () from /usr/lib/xorg/modules/drivers/pvrsgx_drv.so
#4  0xb670ae48 in fbdev_crtc_config_resize () from /usr/lib/xorg/modules/drivers/pvrsgx_drv.so
#5  0x004fd378 in xf86RandR12ScreenSetSize (pScreen=0x61d318, width=<optimized out>, height=<optimized out>, mmWidth=211, mmHeight=127)
    at ../../../../../../hw/xfree86/modes/xf86RandR12.c:698
#6  0x0053255e in ProcRRSetScreenConfig (client=<optimized out>) at ../../../../randr/rrscreen.c:1088
#7  0x004ab3e6 in Dispatch () at ../../../../dix/dispatch.c:478
#8  0x004adfbe in dix_main (argc=11, argv=0xbe9aec94, envp=<optimized out>) at ../../../../dix/main.c:276
#9  0xb6a0b524 in __libc_start_main (main=0x49ef9d <main>, argc=11, argv=0xbe9aec94, init=<optimized out>, fini=0x59e3e1 <__libc_csu_fini>,
    rtld_fini=0xb6f5b6c5 <_dl_fini>, stack_end=0xbe9aec94) at libc-start.c:308
#10 0x0049efd4 in _start ()
```

Oddly enough there is no debug symbols available at all inside the sgx code:

```
(gdb) info locals
No symbol table info available.
```

**Comment by MerlijnWajer** [comment]
This is now fixed by @freemangordon with the new omap ddx + kernel

**Comment by MerlijnWajer** [comment]
As a clarification, rotation doesn't -work- yet, but it doesn't segfault.
