### ISSUE TITLE
Xorg hangs with -video-omap on d4

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#614]
Fairly often xorg will hang using 100% of one core with a black screen on d4. seams to happen most often when turning on the crtc again after blank or rotate.

Seams to be hanging in an ioctl:

```
(gdb) bt
#0  0xb6a1cf08 in ioctl () at ../sysdeps/unix/syscall-template.S:78
#1  0xb6ce1c76 in drmIoctl (fd=14, request=1075602496, arg=0xbefb74a4) at ../xf86drm.c:565
#2  0xb6ce3dd8 in drmCommandWrite (fd=<optimized out>, drmCommandIndex=<optimized out>, data=<optimized out>, size=<optimized out>) at ../xf86drm.c:3025
#3  0xb65f5fbc in  () at /usr/lib/arm-linux-gnueabihf/libsrv_um.so.1
```

```
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
sigreturn({mask=[]})                    = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
sigreturn({mask=[]})                    = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
--- SIGALRM {si_signo=SIGALRM, si_code=SI_KERNEL} ---
sigreturn({mask=[]})                    = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
ioctl(14, _IOC(_IOC_WRITE, 0x64, 0x40, 0x1c), 0xbefb74a4) = 0
... repeats ad infinitum
```

**Comment by IMbackK** [comment]
killing x in this state, or chaning vt dosent get any display back.

**Comment by freemangordon** [comment]
Does it still happen with latest xorg driver?

**Comment by IMbackK** [comment]
yes
